# Generated by Django 3.1 on 2026-01-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilepayment',
            name='bkash_payment_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='mobilepayment',
            name='nagad_order_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='mobilepayment',
            name='mobile_number',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='mobilepayment',
            name='payment_gateway',
            field=models.CharField(choices=[('SSLCommerz', 'SSLCommerz'), ('bKash', 'bKash'), ('Nagad', 'Nagad')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mobilepayment',
            name='status',
            field=models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='initiated', max_length=20),
        ),
        migrations.AlterField(
            model_name='mobilepayment',
            name='verification_response',
            field=models.TextField(blank=True, default=''),
        ),
    ]
