# Generated by Django 3.1 on 2026-01-25 03:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0003_auto_20260125_0352'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobilepayment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.AlterModelOptions(
            name='orderproduct',
            options={},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={},
        ),
        migrations.RenameField(
            model_name='mobilepayment',
            old_name='bank_transaction_id',
            new_name='transaction_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='merchant_transaction_id',
            new_name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='mobilepayment',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='mobilepayment',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='mobilepayment',
            name='gateway_response',
        ),
        migrations.RemoveField(
            model_name='mobilepayment',
            name='gateway_transaction_id',
        ),
        migrations.RemoveField(
            model_name='mobilepayment',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='mobilepayment',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='mobilepayment',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='mobilepayment',
            name='sslcommerz_bank_tran_id',
        ),
        migrations.RemoveField(
            model_name='mobilepayment',
            name='sslcommerz_session_key',
        ),
        migrations.RemoveField(
            model_name='mobilepayment',
            name='sslcommerz_val_id',
        ),
        migrations.RemoveField(
            model_name='mobilepayment',
            name='status_message',
        ),
        migrations.RemoveField(
            model_name='mobilepayment',
            name='user_agent',
        ),
        migrations.RemoveField(
            model_name='mobilepayment',
            name='verification_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='grand_total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='post_code',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_charge',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sslcommerz_session_key',
        ),
        migrations.RemoveField(
            model_name='order',
            name='sslcommerz_tran_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='currency_amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='sslcommerz_bank_tran_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='sslcommerz_card_no',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='sslcommerz_card_type',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='sslcommerz_val_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='verification_response',
        ),
        migrations.AlterField(
            model_name='mobilepayment',
            name='mobile_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='mobilepayment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AlterField(
            model_name='mobilepayment',
            name='payment_gateway',
            field=models.CharField(choices=[('bKash', 'bKash'), ('Nagad', 'Nagad')], max_length=20),
        ),
        migrations.AlterField(
            model_name='mobilepayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('initiated', 'Initiated'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='mobilepayment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mobilepayment',
            name='verification_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_note',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_total',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.payment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='New', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='tax',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.payment'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='product_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_paid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_gateway',
            field=models.CharField(default='PayPal', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
